# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f011b56d389439c861e11ad0d307baa437d33e1c325bb90c9959b1008421c090327e127341d44962893346b3124b304d0ccb39fdad3dc98163c4acc11f9f5511

test:
  secret_key_base: 6a1848104906e94b357a277ea2038c1a6faab333261c1801c9a25c7d719243198846fcd691c8d02f9e6702253ab305bb6572c9abaf84c2a0d8067a35e9c06e43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
