class AddResponses < ActiveRecord::Migration
  def change
  	jb = Response.new(:text => "so dumb", :agreesNum => 1, :doctor_id => 1, :is_doctor => 1, :question_id => 1, :option_num => 1)
    jb.save(:validate => false)
    ph = Response.new(:text => "so beautiful", :agreesNum => 2, :doctor_id =>2, :is_doctor => 1, :question_id => 2, :option_num => 2)
    ph.save(:validate => false)
    mc = Response.new(:text => "so smart", :agreesNum => 3, :doctor_id => 3, :is_doctor => 1, :question_id => 3, :option_num => 1)
    mc.save(:validate => false)
    bo = Response.new(:text => "so insightful", :agreesNum => 4, :doctor_id => 4, :is_doctor => 1, :question_id => 4, :option_num => 2)
    bo.save(:validate => false)
    sc = Response.new(:text => "so helpful", :agreesNum => 5, :doctor_id => 5, :is_doctor => 1, :question_id => 5, :option_num => 1)
    sc.save(:validate => false)
    jo = Response.new(:text => "so life-changing!", :agreesNum => 6, :doctor_id => 6, :is_doctor => 1, :question_id => 6, :option_num => 2)
    jo.save(:validate => false)
    jc = Response.new(:text => "so dumbbbb", :agreesNum => 1, :user_id => 1, :is_doctor => 0, :question_id => 7, :option_num => 1)
    jc.save(:validate => false)
    pc = Response.new(:text => "so beautifulllll", :agreesNum => 2, :user_id =>2, :is_doctor => 0, :question_id => 8, :option_num => 2)
    pc.save(:validate => false)
    md = Response.new(:text => "so smarttttt", :agreesNum => 3, :user_id => 3, :is_doctor => 0, :question_id => 9, :option_num => 1)
    md.save(:validate => false)
    bc = Response.new(:text => "so insightfullll", :agreesNum => 4, :user_id => 4, :is_doctor => 0, :question_id => 10, :option_num => 2)
    bc.save(:validate => false)
    sd = Response.new(:text => "so helpfullll", :agreesNum => 5, :user_id => 5, :is_doctor => 0, :question_id => 11, :option_num => 1)
    sd.save(:validate => false)
    jf = Response.new(:text => "so life-changingggg!", :agreesNum => 6, :user_id => 6, :is_doctor => 0, :question_id => 12, :option_num => 2)
    jf.save(:validate => false)
  end
end